import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

const sources = {
  XTERM_JS: resolve(projectRoot, 'node_modules/@xterm/xterm/lib/xterm.js'),
  XTERM_CSS: resolve(projectRoot, 'node_modules/@xterm/xterm/css/xterm.css'),
  ADDON_FIT_JS: resolve(projectRoot, 'node_modules/@xterm/addon-fit/lib/addon-fit.js'),
};

const out = resolve(projectRoot, 'src/components/terminal/xtermBundle.ts');
mkdirSync(dirname(out), { recursive: true });

const header =
  '// AUTO-GENERATED by scripts/embed-xterm.mjs — do not edit by hand.\n' +
  '// Regenerate with `npm run embed:xterm`.\n\n';

const parts = [];
parts.push(header);
for (const [name, file] of Object.entries(sources)) {
  const text = readFileSync(file, 'utf8');
  parts.push(`export const ${name} = ${JSON.stringify(text)};\n`);
}

writeFileSync(out, parts.join('\n'));
console.log(`embed-xterm: wrote ${out}`);
