export { WSClient, type ConnectionState, type DemoBackendLike, type WSClientOptions } from './WSClient';
export { WSError, isWSError } from './errors';
export { AppStateBinder } from './AppStateBinder';
export { BackoffScheduler, type BackoffOptions } from './reconnect';
export {
  ALL_EVENT_NAMES,
  type AuthParams,
  type DeviceTheme,
  type ThemeChange,
  type EventData,
  type EventDataMap,
  type EventName,
  type MethodMap,
  type MethodName,
  type MethodParams,
  type MethodResult,
  type Pairing,
  type PaneOwner,
  type PaneOwnership,
  type Project,
  type RegisterParams,
  type Split,
  type SplitDirection,
  type SplitNode,
  type SplitPosition,
  type Tab,
  type TabArea,
  type TabKind,
  type TerminalCell,
  type TerminalCells,
  type TerminalOutput,
  type TerminalSnapshot,
  type Workspace,
  type Worktree,
  type GitFile,
  type GitFileStatus,
  type VCSStatus,
  type VCSBranches,
  type VCSPRCreated,
  type VCSPullRequest,
  type VCSPRChecks,
  type VCSPRChecksStatus,
  type VCSPRMergeStateStatus,
  type VCSMergeMethod,
} from './protocol';
